name: Selenium TestNG Pipeline

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  run-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Execute Tests
        run: mvn clean test

      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Reports
          path: |
            test-output/
            target/surefire-reports/